services:
    economy-service:
        build: .
        ports:
            - 2009:2009
        restart: unless-stopped
        volumes:
            - /data/economy:/economy/data

volumes:
    economy-data:
